version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "03:00"
      timezone: "Europe/London"
    open-pull-requests-limit: 10
    versioning-strategy: increase
    commit-message:
      prefix: "chore"
      include: "scope"

    groups:
      oxc:
        patterns:
          - "oxlint"
          - "oxlint-*"
          - "oxfmt"

      commit-lint:
        patterns:
          - "@commitlint/*"

      semantic-release:
        patterns:
          - "@semantic-release/*"
          - "semantic-release"

      tooling:
        patterns:
          - "@types/node"
          - "concurrently"
          - "husky"
          - "rimraf"

      transitive-deps:
        patterns:
          - "*"
